{% set name = "libtree" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/haampie/libtree/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 20d3cd66f5c74058de9dd594af8ffd639c795d27ab435c588a3cd43911c1604f

build:
  number: 0
  skip: true  # [win]
  script:
    - set -ex  # [unix]
    - CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"  # [osx]
    - cmake ${CMAKE_ARGS} -G Ninja -B _build  # [unix]
    - cmake -DCMAKE_INSTALL_PREFIX=%PREFIX% -G Ninja -B _build  # [win]
    - cmake --build _build
    - ctest --test-dir _build --output-on-failure  # [build_platform != target_platform]
    - cmake --install _build

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - elfio
    - cxxopts
    - termcolor-cpp

test:
  commands:
    - {{ name }} --version  # [build_platform == target_platform]

about:
  home: https://github.com/haampie/libtree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ldd as a tree with an option to bundle dependencies into a single folder

extra:
  recipe-maintainers:
    - awvwgk
    - matthiasdiener
