{% set name = "libtree" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/haampie/libtree/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6f7b069a8e5d86741e18a4c8a7e835ac530ae012dfc9509e00ffa694aa6818b1

build:
  number: 0
  skip: true  # [win]
  script:
    - set -ex  # [unix]
    - make
    - make check  # [build_platform == target_platform]
    - make install

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - {{ name }} --version  # [build_platform == target_platform]

about:
  home: https://github.com/haampie/libtree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ldd as a tree with an option to bundle dependencies into a single folder

extra:
  recipe-maintainers:
    - awvwgk
    - matthiasdiener
