{% set name = "libtree" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/haampie/libtree/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8057edb2dd77b0acf6ceab6868741993979dccd41fc41a58bde743f11666d781

build:
  number: 0
  skip: true  # [win]
  script:
    - set -ex  # [unix]
    - make
    - make -i check  # [build_platform == target_platform]
    - make install

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - {{ name }} --version  # [build_platform == target_platform]

about:
  home: https://github.com/haampie/libtree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ldd as a tree with an option to bundle dependencies into a single folder

extra:
  recipe-maintainers:
    - awvwgk
    - matthiasdiener
